### ISSUE TITLE
关于访问权限

### ISSUE THREAD

**Issue by Nemo1166** [Jaggle/wp-geetest-3.0#2]
您好，我按照您的提示在服务器中安装了插件，但是当我打开管理页面时提示“抱歉，您不能访问此页面。”我已经按照说明向web用户授予了权限，但仍不能打开设置页面。

**Comment by jjsty1e** [comment]
谢谢反馈

**Comment by jjsty1e** [comment]
758d53ed97afe9d0db40651cf46e757aa871f49a

**Comment by jjsty1e** [comment]
已修复

**Comment by Nemo1166** [comment]
> [758d53e](https://github.com/Jaggle/wp-geetest-3.0/commit/758d53ed97afe9d0db40651cf46e757aa871f49a)

感谢debug，另外在如下图的按钮对应的URL仍是不正确的，建议也修改一下

![](https://blog.lanshow.tk/wp-content/uploads/2018/12/Snipaste_2018-12-09_02-17-04.png)

**Comment by jjsty1e** [comment]
已修复，😅

**Comment by jjsty1e** [comment]
afef128c7d3df85c498f84f16322d95438e73798

**Comment by Nemo1166** [comment]
感谢！（刚想说在这一行结果已经修复了😂）
