### ISSUE TITLE
安装后有一个PHP错误

### ISSUE THREAD

**Issue by today4king** [Jaggle/wp-geetest-3.0#3]
file_put_contents(/srv/jinzhao_me/wp-content/plugins/wp-geetest-3.0/config.php): failed to open stream: Permission denied

安装后可以正常使用，但是会显示这个错误。

**Comment by jjsty1e** [comment]
权限问题:

```
chown -R www:www /srv/jinzhao_me/wp-content/plugins/wp-geetest-3.0
```

**Comment by today4king** [comment]
权限开到777了，不过我的环境比较特别是跑在php-fpm构建的docker容器里的。

**Comment by jjsty1e** [comment]
如果777还是不行的话，我目前也不知道如何处理了，我没有用docker，无法提供额外的帮助了，除非你提供更多详细的信息过来
