### ISSUE TITLE
IE 11 windows10 没有极验出现

### ISSUE THREAD

**Issue by snsnsjsn** [Jaggle/wp-geetest-3.0#7]
如图

![image](https://user-images.githubusercontent.com/11435527/55723122-bc951280-5a3a-11e9-8841-e83c99a9a8d0.png)

360，chrome ，edge都可以
![image](https://user-images.githubusercontent.com/11435527/55723195-f8c87300-5a3a-11e9-9483-11178a5aa2b7.png)

**Comment by jjsty1e** [comment]
抱歉，我无法对IE做验证。
