### ISSUE TITLE
WordPress 5.2.1 启用插件后存在一个bug

### ISSUE THREAD

**Issue by sy-records** [Jaggle/wp-geetest-3.0#8]
启用插件可能会导致后台无法正常编辑主题文件

**Comment by jjsty1e** [comment]
没遇到过这种问题，🙂，需要更多信息。

**Comment by sy-records** [comment]
额，好吧。在我博客发现的这个问题。刚才使用测试环境又测试了一下，依旧有问题。
![image](https://user-images.githubusercontent.com/33931153/58243672-aab9c580-7d83-11e9-896c-82e75e3c0887.png)

> 没装这个插件是正常操作的😂

停用插件后恢复正常

![image](https://user-images.githubusercontent.com/33931153/58243765-dccb2780-7d83-11e9-95ec-d846534a2043.png)

-------
该插件给的`777`权限

php 7.2.6
wordpress 5.2.1

**Comment by sy-records** [comment]
后台大部分都无法正常操作。。

**Comment by sy-records** [comment]
默认主题，单独一个插件

**Comment by sy-records** [comment]
自己重写了。
